title: 计算神经语言学论坛
description: 一个专注于心理语言学、神经科学和计算建模交叉领域的学术论坛
baseurl: "/Computational-Neurolinguistics-Forum"
url: "https://xufengduan.github.io"

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - scripts
  - Makefile

# 集合配置
collections:
  events:
    output: true
    permalink: /events/:path/ 